package uiharu.persistence.entity;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;
import java.lang.String;
import java.lang.Integer;

/**
 * The entity of the table "t_client_record".
 * @author Kahle
 * @date 2020-05-24T22:43:33.621+0800
 */
@Data
public class ClientRecord implements Serializable {

    /* (Start) This will be covered, please do not modify. */
    /**
     * 主键
     */
    private Integer id;
    /**
     * 设备
     */
    private String deviceId;
    /**
     * 应用
     */
    private String appId;
    /**
     * 名称
     */
    private String appName;
    /**
     * 类型
     */
    private String appType;
    /**
     * 版本
     */
    private String appVersion;
    /**
     * 系统名称
     */
    private String systemName;
    /**
     * 系统版本
     */
    private String systemVersion;
    /**
     * 系统位数
     */
    private String systemBits;
    /**
     * 用户ID
     */
    private String userId;
    /**
     * 用户名称
     */
    private String userName;
    /**
     * 描述
     */
    private String description;
    /**
     * 注册时间
     */
    private Date registerTime;
    /**
     * 创建者
     */
    private String createUser;
    /**
     * 创建时间
     */
    private Date createDate;
    /**
     * 修改者
     */
    private String updateUser;
    /**
     * 修改时间
     */
    private Date updateDate;
    /**
     * 数据状态
     */
    private Integer aliveFlag;
    /* (End) This will be covered, please do not modify. */
    /* Generated by artoria-extend in 2020-05-24T22:43:34.166+0800. */

}
