package uiharu.pojo.vo;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;
import java.lang.String;
import java.lang.Integer;

/**
 * The vo of the table "t_trace_event_record".
 * @author Kahle
 * @date 2020-05-24T22:44:22.212+0800
 */
@Data
public class TraceEventRecordVO implements Serializable {

    /* (Start) This will be covered, please do not modify. */
    /**
     * 事件ID
     */
    private String id;
    /**
     * 令牌ID
     */
    private String tokenId;
    /**
     * 用户ID
     */
    private String userId;
    /**
     * 事件时间
     */
    private Date time;
    /**
     * 客户端ID
     */
    private String clientId;
    /**
     * 事件级别
     */
    private Integer level;
    /**
     * 客户端的应用ID
     */
    private String clientAppId;
    /**
     * 客户端名称
     */
    private String clientName;
    /**
     * 客户端用户代理
     */
    private String clientUserAgent;
    /**
     * 客户端的网络地址
     */
    private String clientNetAddress;
    /**
     * 服务器ID
     */
    private String serverId;
    /**
     * 服务器的应用名称
     */
    private String serverAppId;
    /**
     * 接口标识
     */
    private String interfaceId;
    /**
     * 请求的来源
     */
    private String requestReferer;
    /**
     * 请求的方法
     */
    private String requestMethod;
    /**
     * 请求的地址
     */
    private String requestAddress;
    /**
     * 请求时的输入信息
     */
    private String requestInput;
    /**
     * 响应时的输出信息
     */
    private String responseOutput;
    /**
     * 错误信息
     */
    private String errorMessage;
    /**
     * 处理时间
     */
    private Integer processTime;
    /**
     * 创建者
     */
    private String createUser;
    /**
     * 创建时间
     */
    private Date createDate;
    /**
     * 修改者
     */
    private String updateUser;
    /**
     * 修改时间
     */
    private Date updateDate;
    /**
     * 数据状态
     */
    private Integer aliveFlag;
    /* (End) This will be covered, please do not modify. */
    /* Generated by artoria-extend in 2020-05-24T22:44:22.626+0800. */

}
