package uiharu.persistence.mapper;

import uiharu.persistence.entity.ClientRecord;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 * ClientRecordMapper.
 * @author Kahle
 * @date 2020-05-24T22:43:33.621+0800
 */
@Mapper
public interface ClientRecordMapper {

    /* (Start) This will be covered, please do not modify. */
    /**
     * Insert.
     * @param record The object to insert
     * @return Number of rows effected
     */
    int insert(ClientRecord record);

    /**
     * Insert batch.
     * @param recordList A list of records to insert
     * @return Number of rows effected
     */
    int insertBatch(@Param("recordList") List<ClientRecord> recordList);

    /**
     * Insert selective.
     * @param record The object to insert
     * @return Number of rows effected
     */
    int insertSelective(ClientRecord record);

    /**
     * Delete by primary key.
     * @param id Primary key
     * @param updateUser Current operator
     * @return Number of rows effected
     */
    int deleteByPrimaryKey(@Param("id") Integer id, @Param("updateUser") String updateUser);

    /**
     * Delete by primary key list.
     * @param idList Primary key list
     * @param updateUser Current operator
     * @return Number of rows effected
     */
    int deleteByPrimaryKeyList(@Param("idList") List<Integer> idList, @Param("updateUser") String updateUser);

    /**
     * Delete selective.
     * @param record Delete conditions
     * @return Number of rows effected
     */
    int deleteSelective(ClientRecord record);

    /**
     * Update by primary key.
     * @param record Content to be updated
     * @return Number of rows effected
     */
    int updateByPrimaryKey(ClientRecord record);

    /**
     * Update by primary key selective.
     * @param record Content to be updated
     * @return Number of rows effected
     */
    int updateByPrimaryKeySelective(ClientRecord record);

    /**
     * Conditional counting.
     * @param record Query condition
     * @return Count result
     */
    int countSelective(ClientRecord record);

    /**
     * Query by primary key.
     * @param id Primary key
     * @return Query result
     */
    ClientRecord queryByPrimaryKey(@Param("id") Integer id);

    /**
     * Query by primary key list.
     * @param idList Primary key list
     * @return Query result list
     */
    List<ClientRecord> queryByPrimaryKeyList(@Param("idList") List<Integer> idList);

    /**
     * Find one.
     * @param record Query condition
     * @return Query result
     */
    ClientRecord findOne(ClientRecord record);

    /**
     * Query selective.
     * @param record Query condition
     * @return Query result list
     */
    List<ClientRecord> querySelective(ClientRecord record);
    /* (End) This will be covered, please do not modify. */
    /* Generated by artoria-extend in 2020-05-24T22:43:34.065+0800. */

}
