package uiharu.pojo.dto;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;
import java.lang.String;
import java.lang.Integer;

/**
 * The dto of the table "t_event_record".
 * @author Kahle
 * @date 2020-05-24T22:44:07.754+0800
 */
@Data
public class EventRecordDTO implements Serializable {

    /* (Start) This will be covered, please do not modify. */
    /**
     * 事件ID
     */
    private String id;
    /**
     * 令牌ID
     */
    private String tokenId;
    /**
     * 用户ID
     */
    private String userId;
    /**
     * 事件时间
     */
    private Date time;
    /**
     * 客户端ID
     */
    private String clientId;
    /**
     * 事件名称
     */
    private String name;
    /**
     * 事件Code
     */
    private String code;
    /**
     * 事件类型
     */
    private String type;
    /**
     * 事件级别
     */
    private Integer level;
    /**
     * 事件描述
     */
    private String description;
    /**
     * 事件变量的JSON
     */
    private String variablesJson;
    /**
     * 事件的提供者
     */
    private String provider;
    /**
     * 创建者
     */
    private String createUser;
    /**
     * 创建时间
     */
    private Date createDate;
    /**
     * 修改者
     */
    private String updateUser;
    /**
     * 修改时间
     */
    private Date updateDate;
    /**
     * 数据状态
     */
    private Integer aliveFlag;
    /* (End) This will be covered, please do not modify. */
    /* Generated by artoria-extend in 2020-05-24T22:44:08.141+0800. */

}
